### ISSUE TITLE
What is the difference between hootsuite/akka-persistence-redis ?

### ISSUE THREAD

**Issue by l15k4** [safety-data/akka-persistence-redis#18]
Hey,

would you please add a paragraph about why should people use this over hootsuite/akka-persistence-redis ?

I'm currently using the above mentioned plugin but for some reason ~ 1 of 1M messages fails to be persisted and I cannot figure out why, so I'm wondering whether to switch to this plugin implementation.

**Comment by satabin** [comment]
I am not sure I will add such a section because it may be difficult to maintain.
The project was started to add following features that we were missing in the hootsuite persistence plugin:

 - event tagging
 - use of akka serialization framework to choose serialization format
 - implementation of journal queries

**Comment by epot** [comment]
Just as @l15k4  I am currently using the hootsuite version. In order to be able to switch (as I am running on Azure), I would need to implement a similar pull request as https://github.com/hootsuite/akka-persistence-redis/pull/21. Would it be something I can try to implement in this component and that would get accepted?

**Comment by satabin** [comment]
Hi,

From what I see, it means adding a `max-replay-message` integer configuration key. It would totally be accepted.

Is overriding key namespace also required? I would also accept that, but I would prefer two PR, one for each addition.

**Comment by epot** [comment]
Great for the first one, I will start a PR right now.

How are the keys named today? Basically I have several Akka Persistence independent instances writing to the same Redis Cache, so I need to have them writing to different keys.

**Comment by epot** [comment]
And just out of curiosity, do you consider this component as production ready? The 0.3.0 version number frightens me a bit :).

**Comment by satabin** [comment]
For your use you will also need to be able to override the namespace.

I'd say it can be used in production, we use it internally and never experienced problems with medium amount of events per seconds. The version number is low because for the moment, not much features are present, but I think it is quite stable.

**Comment by epot** [comment]
Ok thanks. Will start working on the 2 PRs right now :).

**Comment by epot** [comment]
Actually it looks like I do not have the issue I had with Azure before, where I needed to have a max-replay-message. And if I understand correctly, I can use the persistenceId to write in different keys. so maybe I do not need any change after all :).
